server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.248.142:3306/sale?useUnicode=true&amp;characterEncoding=UTF-8
    username: sale
    password: csfdevyw123
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crmww.sale.model

mapper:
    mappers: com.crmww.sale.util.MyMapper
    not-empty: false
    identity: MYSQLs