server:
  port: 8080

spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crmww.sale.model

mapper:
    mappers: com.crmww.sale.util.MyMapper
    not-empty: false
    identity: MYSQLs


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback-spring.xml
  path: D:/saleLog